Added new codes
r4digital/node-occurrence-codes pull request #3
Opened 2021-04-23 12:56 UTC by kaieguex

Adicionado ocorrência de Registro rejeitado - Agência ou Conta do Dédito Inválida

2021-04-26 19:02 UTC, henrique502 commented on src/transfer/BaasTr´ansferCode.ts
> +   * Registro rejeitado - Agência ou Conta do Dédito Inválida
Ajustar de Dédito  para Débito

2021-04-26 19:05 UTC, kaieguex commented on src/transfer/BaasTr´ansferCode.ts
> +   * Registro rejeitado - Agência ou Conta do Dédito Inválida
Ajustado

2021-04-27 13:51 UTC, henrique502 requested changes
Revisar os nomes, existe uma renomeação do arquivo indevida, tem que ajustar a descrição ela contém erros

2021-04-27 18:06 UTC, henrique502 approved these changes

2021-04-27 18:06 UTC, merged